sudo: false
language: go
go:
- 1.7
env:
  global:
  matrix:
  - TEST_TYPE=small
install:
  - export TMPDIR=$HOME/tmp
  - mkdir -p $TMPDIR
  - glide install
script:
  - go test -tags=$TEST_TYPE -v
notifications:
  email: false
