sudo: false
language: go
go:
  - 1.7
before_install:
  - go get github.com/Masterminds/glide
env:
  global:
  matrix:
  - TEST_TYPE=small
install:
  - export TMPDIR=$HOME/tmp
  - mkdir -p $TMPDIR
  - glide install
notifications:
  email: false
